# Explorando Dataset com pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./arquivos/insurance.csv')

In [7]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [9]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [10]:
df.shape

(1338, 7)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

### Acessando Dados

In [12]:
# acessando coluna especifica

df['age'].head()

0    19
1    18
2    28
3    33
4    32
Name: age, dtype: int64

In [13]:
df.age.head()

0    19
1    18
2    28
3    33
4    32
Name: age, dtype: int64

In [ ]:
# acessando uma linha especifica ou otras posuições
df['age'][3:10]

3    33
4    32
5    31
6    46
7    37
8    37
9    60
Name: age, dtype: int64

In [17]:
# df['age', 'bmi', 'smoker'].head() os items tem que ser passado como uma lista
df[['age', 'bmi', 'smoker']].head()

   age     bmi smoker
0   19  27.900    yes
1   18  33.770     no
2   28  33.000     no
3   33  22.705     no
4   32  28.880     no

In [ ]:
df.loc[0]

age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
charges     16884.924
Name: 0, dtype: object

In [20]:
df.loc[10, 'region']

'northeast'

In [22]:
df.loc[10:15, ['region', 'charges']]

       region     charges
10  northeast   2721.3208
11  southeast  27808.7251
12  southwest   1826.8430
13  southeast  11090.7178
14  southeast  39611.7577
15  southwest   1837.2370

In [ ]:
# acessa por indice e não por rotulo igual ao loc
# tem que pegar a posição na tabela
df.iloc[10:15, 5:7]

       region     charges
10  northeast   2721.3208
11  southeast  27808.7251
12  southwest   1826.8430
13  southeast  11090.7178
14  southeast  39611.7577

### Filtros com Pandas

In [27]:
# pode inserir uma lógica dentro do loc para retornar resultados
df.loc[df['age'] >= 63]

      age     sex     bmi  children smoker     region      charges
26     63  female  23.085         0     no  northeast  14451.83515
33     63    male  28.310         0     no  northwest  13770.09790
62     64    male  24.700         1     no  northwest  30166.61817
94     64  female  31.300         2    yes  southwest  47291.05500
109    63    male  35.090         0    yes  southeast  47055.53210
170    63    male  41.470         0     no  southeast  13405.39030
175    63  female  37.700         0    yes  southwest  48824.45000
199    64  female  39.330         0     no  northeast  14901.51670
208    63  female  31.800         0     no  southwest  13880.94900
244    63  female  27.740         0    yes  northeast  29523.16560
251    63  female  32.200         2    yes  southwest  47305.30500
287    63  female  26.220         0     no  northwest  14256.19280
328    64  female  33.800         1    yes  southwest  47928.03000
335    64    male  34.500         0     no  southwest  13822.80300
343    63    male  36.765         0     no  northeast  13981.85035
378    64  female  30.115         3     no  northwest  16455.70785
398    64    male  25.600         2     no  southwest  14988.43200
402    64  female  32.965         0     no  northwest  14692.66935
418    64    male  39.160         1     no  southeast  14418.28040
419    63  female  26.980         0    yes  northwest  28950.46920
420    64    male  33.880         0    yes  southeast  46889.26120
480    63    male  41.325         3     no  northwest  15555.18875
534    64    male  40.480         0     no  southeast  13831.11520
542    63  female  36.300         0     no  southeast  13887.20400
550    63    male  30.800         0     no  southwest  13390.55900
603    64  female  39.050         3     no  southeast  16085.12750
635    64    male  38.190         0     no  northeast  14410.93210
664    64  female  22.990         0    yes  southeast  27037.91410
752    64    male  37.905         0     no  northwest  14210.53595
768    64  female  39.700         0     no  southwest  14319.03100
801    64  female  35.970         0     no  southeast  14313.84630
825    64  female  31.825         2     no  northeast  16069.08475
830    63    male  33.100         0     no  southwest  13393.75600
890    64  female  26.885         0    yes  northwest  29330.98315
908    63    male  39.800         3     no  southwest  15170.06900
962    63  female  35.200         1     no  southeast  14474.67500
997    63  female  36.850         0     no  southeast  13887.96850
1051   64    male  26.410         0     no  northeast  14394.55790
1068   63    male  21.660         1     no  northwest  14349.85440
1071   63    male  31.445         0     no  northeast  13974.45555
1079   63    male  33.660         3     no  southeast  15161.53440
1125   63  female  25.080         0     no  northwest  14254.60820
1236   63  female  21.660         0     no  northeast  14449.85440
1241   64    male  36.960         2    yes  southeast  49577.66240
1265   64    male  23.760         0    yes  southeast  26926.51440

In [28]:
df.loc[df['smoker'] == 'yes'].shape

(274, 7)

In [32]:
df.loc[
    (df['smoker'] == 'yes')
    &
    (df['charges'] < 14000)
    &
    (df['region'] == 'northeast')
]

      age   sex     bmi  children smoker     region      charges
250    18  male  17.290         2    yes  northeast  12829.45510
1033   18  male  21.565         0    yes  northeast  13747.87235

In [31]:
df.loc[
    (df['smoker'] == 'yes')
    |
    (df['sex'] == 'male')
]

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1325   61    male  33.535         0     no  northeast  13143.33665
1327   51    male  30.030         1     no  southeast   9377.90470
1329   52    male  38.600         2     no  southwest  10325.20600
1333   50    male  30.970         3     no  northwest  10600.54830
1337   61  female  29.070         0    yes  northwest  29141.36030

[791 rows x 7 columns]

In [ ]:
df.query("age > 50")

      age     sex    bmi  children smoker     region      charges
9      60  female  25.84         0     no  northwest  28923.13692
11     62  female  26.29         0    yes  southeast  27808.72510
13     56  female  39.82         0     no  southeast  11090.71780
16     52  female  30.78         1     no  northeast  10797.33620
18     56    male  40.30         0     no  southwest  10602.38500
...   ...     ...    ...       ...    ...        ...          ...
1327   51    male  30.03         1     no  southeast   9377.90470
1329   52    male  38.60         2     no  southwest  10325.20600
1330   57  female  25.74         2     no  southeast  12629.16560
1332   52  female  44.70         3     no  southwest  11411.68500
1337   61  female  29.07         0    yes  northwest  29141.36030

[356 rows x 7 columns]

In [38]:
df.query("region == 'northeast'").shape[0]

324

In [39]:
df.query("smoker == 'yes' and age > 40")

      age     sex     bmi  children smoker     region      charges
11     62  female  26.290         0    yes  southeast  27808.72510
39     60    male  39.900         0    yes  southwest  48173.36100
52     48    male  28.000         1    yes  southwest  23568.27200
55     58    male  36.955         2    yes  northwest  47496.49445
58     53  female  22.880         1    yes  southeast  23244.79020
...   ...     ...     ...       ...    ...        ...          ...
1303   43    male  27.800         0    yes  southwest  37829.72420
1304   42    male  24.605         2    yes  northeast  21259.37795
1321   62    male  26.695         0    yes  northeast  28101.33305
1323   42  female  40.370         2    yes  southeast  43896.37630
1337   61  female  29.070         0    yes  northwest  29141.36030

[125 rows x 7 columns]