In [2]:
import math

In [4]:
def fatorial(n):
    if  n==0 or n==1: 
        return 1
    
    resultado = 1
    for i in range(2, n+1):
        resultado *= i
    return resultado

In [5]:
fatorial(5)

120

In [6]:
math.factorial(5)

120

# Pandas

In [3]:
import pandas as pd
import numpy as np

In [6]:
iris = pd.read_csv('IRIS.csv')

In [7]:
np.random.rand(3)

array([0.36563983, 0.51928079, 0.1346509 ])

In [11]:
# array de uma dimensão
s = pd.Series([1,2,np.nan,4,5])

In [12]:
s

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [13]:
type(s)

pandas.core.series.Series

In [17]:
# Data frame - tabela
print(type(iris))
iris

<class 'pandas.core.frame.DataFrame'>

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# Ao criar um DataFrame os dados são guardados em formato de lista
pessoas = pd.DataFrame(
    {
        'Nome': ['Anna', 'Maria', 'MingHao'],
        'Idade': ['27', '21', '28']
    }
)

In [ ]:
pessoas

      Nome Idade
0     Anna    27
1    Maria    21
2  MingHao    28